# Generated by Django 3.2.12 on 2022-05-07 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0004_alter_feed_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bk_feed', to=settings.AUTH_USER_MODEL),
        ),
    ]
