# Generated by Django 3.2.12 on 2022-05-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_feed_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='bookmark',
            new_name='bookmark_user',
        ),
    ]
