# Generated by Django 3.2.12 on 2022-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20220502_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image_url',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
