# Generated by Django 3.2.12 on 2022-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20220503_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='hashtag_feeds', to='feeds.Hashtag'),
        ),
    ]
