# Generated by Django 3.2.12 on 2022-05-03 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0009_alter_feed_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='tag_users',
            field=models.ManyToManyField(blank=True, related_name='tag_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
